export { default as Banner } from "./Banner";
export { default as WebDesignServices } from "./WebDesignServices";
export { default as OurSolutions } from "./OurSolutions";
export { default as IndustriesServed } from "./IndustriesServed";
export { default as Approach } from "./Approach";
export { default as PromoSection } from "./PromoSection";
export { default as ServiceOfferings } from "./ServiceOfferings";
export { default as Faq } from "./Faq";
export { default as WebDesignFeatures } from "./WebDesignFeatures";
